### ISSUE TITLE
Recognizes perl by file extension rather than document type

### ISSUE THREAD

**Issue by johndog** [hitode909/vscode-perl-outline#9]
If a .cmd or .sh file is actually a perl script, you can tell vscode by changing the file type to Perl.

vscode-perl-outline doesn't honor this designation, though, and still won't outline the file.

**Comment by NorthboundTrain** [comment]
This can be "fixed" locally by editing one of the project files. For me (MacOS) the file was at:

~/.vscode/extensions/hitode909.perl-outline-0.0.6/out/extension.js

Other platforms may put the file in a different place.

Locate this block:

    context.subscriptions.push(vscode.languages.registerDocumentSymbolProvider([
        { language: 'perl', pattern: '**/*.{pm,pl,t,ph}' },
        { language: 'perl', scheme: 'untitled' },

and add a line:

    context.subscriptions.push(vscode.languages.registerDocumentSymbolProvider([
        { language: 'perl', pattern: '**/*.{pm,pl,t,ph}' },
        **{ language: 'perl' },**
        { language: 'perl', scheme: 'untitled' },

Since I don't know the implications of creating such a broad DocumentSelector, I am hesitant to submit a pull request. But it seems to be what I would want in any event, and it does work.

**Comment by hitode909** [comment]
@NorthboundTrain Hi, Thank you for your suggestion.
I think, your comment seems right, So I changed the DocumentSelector and released a new version(0.0.7).
Can you try the newer version?

**Comment by NorthboundTrain** [comment]
0.0.7 works for me -- thanks!
